export const firebaseSignupErrorMap = {
  'auth/email-already-in-use': 'Ova email adresa je već registrovana.',
  'auth/invalid-email': 'Email adresa nije ispravna.',
  'auth/user-disabled': 'Ovaj nalog je onemogućen.',
  'auth/user-not-found': 'Nalog sa ovom email adresom ne postoji.',
  'auth/wrong-password': 'Pogrešna lozinka.',
  'auth/weak-password': 'Lozinka mora imati najmanje 6 karaktera.',
  'auth/missing-password': 'Unesite lozinku.',
  'auth/missing-email': 'Unesite email adresu.',
  'auth/invalid-password': 'Lozinka nije ispravna.',
  'auth/operation-not-allowed': 'Ova opcija nije omogućena. Kontaktirajte podršku.',
  'auth/too-many-requests': 'Previše pokušaja. Pokušajte ponovo kasnije.',
  'auth/requires-recent-login': 'Molimo vas da se ponovo prijavite i pokušate ponovo.',
  'auth/account-exists-with-different-credential': 'Nalog sa ovom email adresom već postoji sa drugim načinom prijave.',
  'auth/invalid-credential': 'Neispravni podaci za prijavu.',
  'auth/invalid-verification-code': 'Neispravan verifikacioni kod.',
  'auth/invalid-verification-id': 'Neispravan verifikacioni ID.',
  'auth/expired-action-code': 'Kod je istekao. Zatražite novi.',
  'auth/invalid-action-code': 'Neispravan kod.',
  'auth/invalid-email-verified': 'Email adresa nije verifikovana.',
  'auth/invalid-phone-number': 'Neispravan broj telefona.',
  'auth/missing-verification-code': 'Unesite verifikacioni kod.',
  'auth/missing-verification-id': 'Nedostaje verifikacioni ID.',
  'auth/credential-already-in-use': 'Ovi podaci za prijavu su već iskorišćeni.',
  'auth/email-already-exists': 'Ova email adresa je već iskorišćena.',
  'auth/invalid-login-credentials': 'Neispravni podaci za prijavu.',
  'auth/invalid-api-key': 'Neispravan API ključ.',
  'auth/network-request-failed': 'Greška u mrežnoj konekciji. Proverite internet vezu.',
  'auth/popup-closed-by-user': 'Prozor za prijavu je zatvoren pre završetka.',
  'auth/popup-blocked': 'Vaš pregledač je blokirao prozor za prijavu.',
  'auth/unauthorized-domain': 'Ova domena nije ovlašćena za prijavu.',
  'auth/invalid-tenant-id': 'Neispravan tenant ID.',
  'auth/timeout': 'Vreme za prijavu je isteklo. Pokušajte ponovo.',
  'auth/invalid-code': 'Neispravan kod.',
  'auth/invalid-custom-token': 'Neispravan token.',
  'auth/custom-token-mismatch': 'Token nije validan za ovaj projekat.',
  'auth/invalid-user-token': 'Sesija je istekla. Prijavite se ponovo.',
  'auth/user-token-expired': 'Sesija je istekla. Prijavite se ponovo.',
  'auth/null-user': 'Korisnik nije pronađen.',
  'auth/app-not-authorized': 'Aplikacija nije ovlašćena za korišćenje ovog API ključa.',
  'auth/invalid-continue-uri': 'Neispravan URL za nastavak.',
  'auth/missing-continue-uri': 'Nedostaje URL za nastavak.',
  'auth/unauthorized-continue-uri': 'Neovlašćen URL za nastavak.',
  'auth/invalid-dynamic-link-domain': 'Neispravan domen za dinamički link.',
  'auth/invalid-recipient-email': 'Neispravna email adresa primaoca.',
  'auth/invalid-sender': 'Neispravan pošiljalac.',
  'auth/invalid-message-payload': 'Neispravan sadržaj poruke.',
  'auth/invalid-multi-factor-session': 'Neispravna multi-faktor sesija.',
  'auth/missing-multi-factor-session': 'Nedostaje multi-faktor sesija.',
  'auth/missing-multi-factor-info': 'Nedostaju informacije za multi-faktor autentifikaciju.',
  'auth/invalid-multi-factor-info': 'Neispravne informacije za multi-faktor autentifikaciju.',
  'auth/second-factor-already-in-use': 'Drugi faktor je već u upotrebi.',
  'auth/unsupported-first-factor': 'Prvi faktor nije podržan.',
  'auth/unsupported-persistence-type': 'Ovaj tip sesije nije podržan.',
  'auth/invalid-persistence-type': 'Neispravan tip sesije.',
  'auth/invalid-claims': 'Neispravni zahtevi.',
  'auth/claims-too-large': 'Zahtevi su preveliki.',
  'auth/id-token-expired': 'ID token je istekao.',
  'auth/id-token-revoked': 'ID token je opozvan.',
  'auth/invalid-id-token': 'Neispravan ID token.',
  'auth/user-mismatch': 'Korisnički podaci se ne poklapaju.',
  'auth/provider-already-linked': 'Ovaj način prijave je već povezan sa nalogom.',
  'auth/no-such-provider': 'Ovaj način prijave nije pronađen.',
  'auth/invalid-argument': 'Neispravan argument.',
  'auth/invalid-creation-time': 'Neispravno vreme kreiranja.',
  'auth/invalid-disabled-field': 'Neispravno polje za onemogućavanje.',
  'auth/invalid-display-name': 'Neispravno prikazano ime.',
  'auth/invalid-photo-url': 'Neispravan URL za fotografiju.',
  'auth/invalid-password-hash': 'Neispravan hash lozinke.',
  'auth/invalid-password-salt': 'Neispravan salt za lozinku.',
  'auth/invalid-user-import': 'Neispravan uvoz korisnika.',
  'auth/maximum-user-count-exceeded': 'Prekoračen je maksimalan broj korisnika.',
  'auth/missing-hash-algorithm': 'Nedostaje algoritam za hash.',
  'auth/missing-uid': 'Nedostaje korisnički ID.',
  'auth/reserved-claims': 'Korišćeni su rezervisani zahtevi.',
  'auth/session-cookie-expired': 'Sesija je istekla.',
  'auth/session-cookie-revoked': 'Sesija je opozvana.',
  'auth/uid-already-exists': 'Korisnički ID je već u upotrebi.',
  'auth/phone-number-already-exists': 'Broj telefona je već u upotrebi.',
  'auth/project-not-found': 'Projekat nije pronađen.',
  'auth/insufficient-permission': 'Nemate dozvolu za ovu akciju.',
  'auth/internal-error': 'Došlo je do interne greške. Pokušajte ponovo.',
  // fallback
  'default': 'Došlo je do greške. Pokušajte ponovo.',
}

export const firebaseLoginErrorMap = {
  'Firebase: Error (auth/invalid-credential).': 'Podaci nisu ispravni.',
  'Firebase: Error (auth/invalid-email).': 'Email adresa nije ispravna.',
  'Firebase: Error (auth/user-disabled).': 'Ovaj nalog je onemogućen.',
  'Firebase: Error (auth/user-not-found).': 'Nalog sa ovom email adresom ne postoji.',
  'Firebase: Error (auth/wrong-password).': 'Pogrešna lozinka.',
  'Firebase: Error (auth/too-many-requests).': 'Previše pokušaja. Pokušajte ponovo kasnije.',
  'Firebase: Error (auth/network-request-failed).': 'Greška u mrežnoj konekciji. Proverite internet vezu.',
  'Firebase: Error (auth/internal-error).': 'Došlo je do interne greške. Pokušajte ponovo.',
  'Firebase: Error (auth/invalid-login-credentials).': 'Neispravni podaci za prijavu.',
  'Firebase: Error (auth/popup-closed-by-user).': 'Prozor za prijavu je zatvoren pre završetka.',
  'Firebase: Error (auth/popup-blocked).': 'Vaš pregledač je blokirao prozor za prijavu.',
  'Firebase: Error (auth/unauthorized-domain).': 'Ova domena nije ovlašćena za prijavu.',
  'Firebase: Error (auth/invalid-api-key).': 'Neispravan API ključ.',
  'Firebase: Error (auth/app-not-authorized).': 'Aplikacija nije ovlašćena za korišćenje ovog API ključa.',
  // fallback
  'default': 'Došlo je do greške pri prijavi. Pokušajte ponovo.',
}

export const firebaseResetPasswordErrorMap = {
  'auth/wrong-password': 'Trenutna šifra nije tačna. Pokušajte ponovo.',
  'auth/weak-password': 'Nova šifra je previše slaba. Molimo unesite jaču šifru.',
  'auth/requires-recent-login':
    'Vaša sesija je istekla. Molimo prijavite se ponovo i pokušajte ponovo.',
  'auth/too-many-requests':
    'Previše neuspešnih pokušaja. Molimo pokušajte ponovo kasnije.',
  'auth/network-request-failed': 'Došlo je do greške u mreži. Proverite internet konekciju.',
  'auth/user-not-found': 'Korisnik nije pronađen. Molimo proverite podatke.',
  'auth/internal-error': 'Došlo je do interne greške. Pokušajte ponovo.',
  'auth/invalid-credential': 'Uneta šifra nije tačna. Molimo pokušajte ponovo.'
};